#!/usr/bin/env bash
#
# generate-sponsor-config.sh
#
# Reads .github/FUNDING.yml and writes the GitHub Sponsors handle into
# apps/native/wolfwave/Core/SponsorConfig.generated.swift.
#
# Single source of truth: .github/FUNDING.yml (the same file GitHub renders the
# repo's "Sponsor this project" button from). Run this after editing FUNDING.yml
# and commit both files together. CI runs it too and fails if the generated
# file drifts (see .github/workflows/test.yml).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FUNDING_FILE="$REPO_ROOT/.github/FUNDING.yml"
OUTPUT_FILE="$REPO_ROOT/apps/native/wolfwave/Core/SponsorConfig.generated.swift"

if [[ ! -f "$FUNDING_FILE" ]]; then
    echo "warning: $FUNDING_FILE not found; leaving SponsorConfig unchanged" >&2
    exit 0
fi

# Parse `github: [handle]` or `github: handle` — first match wins.
HANDLE="$(grep -E '^[[:space:]]*github:' "$FUNDING_FILE" \
    | head -n 1 \
    | sed -E 's/^[[:space:]]*github:[[:space:]]*//; s/^\[//; s/\].*$//; s/^["'"'"']//; s/["'"'"']$//; s/[[:space:]]+.*$//' \
    | tr -d ',' )"

if [[ -z "$HANDLE" ]]; then
    echo "warning: no GitHub sponsor handle found in $FUNDING_FILE; leaving SponsorConfig unchanged" >&2
    exit 0
fi

cat > "$OUTPUT_FILE" <<EOF
// AUTO-GENERATED by scripts/generate-sponsor-config.sh — DO NOT EDIT.
// Source: .github/FUNDING.yml
//
// To update: edit .github/FUNDING.yml, then run \`make sponsor-config\` (or
// \`bash scripts/generate-sponsor-config.sh\`) and commit both files.

enum SponsorConfig {
    /// GitHub Sponsors username, parsed from .github/FUNDING.yml at build time.
    static let sponsorUser = "$HANDLE"
}
EOF

echo "Generated $OUTPUT_FILE (sponsor: $HANDLE)"
