// AUTO-GENERATED by scripts/generate-sponsor-config.sh. DO NOT EDIT.
// Source: .github/FUNDING.yml
//
// To update: edit .github/FUNDING.yml, then run `make sponsor-config` (or
// `bash scripts/generate-sponsor-config.sh`) and commit both files.

nonisolated enum SponsorConfig {
    /// GitHub Sponsors username, parsed from .github/FUNDING.yml at build time.
    static let sponsorUser = "nathanialhenniges"
}
